### ISSUE TITLE
Socratic Seminar 12 Reading List (Jan 2023)

### ISSUE THREAD

**Issue by 0xBEEFCAF3** [0xBEEFCAF3/bostonbitdevs#10]
Drop links here!

**Comment by johncantrell97** [comment]
A few lightning-dev topics we could put on the list..

A proposal for modifying the lightning channel protocol to introduce "Tunable Penalties"
https://github.com/JohnLaw2/ln-tunable-penalties/blob/main/tunablepenalties10.pdf

new lightning channel Factory construction proposals based on the above "Tunable Penalties" idea:
https://lists.linuxfoundation.org/pipermail/lightning-dev/2022-December/003782.html

circuitbreaker: an imperfect way to fight back against channel jamming
https://lists.linuxfoundation.org/pipermail/lightning-dev/2022-December/003781.html

**Comment by johncantrell97** [comment]
Not really from December but I had missed it initially.  Interesting idea until better privacy solutions are deployed.

lnproxy:
https://github.com/lnproxy/lnproxy

**Comment by johncantrell97** [comment]
LDK 113 Released! Probably the main change worth noting is the ability to intercept HTLCs.  This enables LDK users to implement just-in-time channel creation, a useful feature for LSPs.

https://github.com/lightningdevkit/rust-lightning/releases/tag/v0.0.113

**Comment by johncantrell97** [comment]
Follow-up on our Full-RBF session last month.  Peter Todd surveyed running bitcoin nodes to find that at least 17% of nodes running 24.x have enabled full-rbf.

https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2022-December/021296.html

**Comment by johncantrell97** [comment]
MAD Transactions: A new 0-conf tx protocol proposal as a way to enable 0-conf txs in a full-rbf world. a game theoretical solution based on mutually assured destruction. 

https://medium.com/@idBrain/mad-transactions-mutual-assured-destruction-transactions-c04f7b5a2fa7

**Comment by edwargix** [comment]
BIP324 v2 P2P Transport Protocol PR merged: https://github.com/bitcoin/bips/pull/1378#event-8155389517

https://bip324.com

**Comment by 0xBEEFCAF3** [comment]
Standard for importing labels was merged https://github.com/bitcoin/bips/blob/master/bip-0329.mediawiki
