### ISSUE TITLE
 Socratic Seminar 13 Reading List (Feb 2023)

### ISSUE THREAD

**Issue by 0xBEEFCAF3** [0xBEEFCAF3/bostonbitdevs#13]
Put links here!!!

**Comment by 0xBEEFCAF3** [comment]
Ledger supporting miniscript / output descriptor / psbtv2 in the new bitcoin app 2.1.0 
https://blog.ledger.com/miniscript-is-coming/

**Comment by 0xBEEFCAF3** [comment]
[bitcoin-dev] SIGHASH_GROUP vs Ephemeral anchors
https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2023-January/021334.html

**Comment by 0xBEEFCAF3** [comment]
An analysis of current coinjoin products
https://is.muni.cz/th/kbvx1/Master_Thesis.pdf

**Comment by 0xBEEFCAF3** [comment]
https://gist.github.com/nopara73/bb17e89d7dc9af536ca41f50f705d329
Discrete Payments through Wabisabi coinjoins and Nostr ecnrypted communication.md

**Comment by 0xBEEFCAF3** [comment]
https://read.pourteaux.xyz/p/illegitimate-bitcoin-transactions
Bitcoin ordinals using tapscript

**Comment by 0xBEEFCAF3** [comment]
Ordinal numbers
https://github.com/casey/ord/blob/master/bip.mediawiki

**Comment by 0xBEEFCAF3** [comment]
[bitcoin-dev] Why Full-RBF Makes DoS Attacks on Multiparty Protocols Significantly More Expensive
https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2023-January/021322.html

**Comment by 0xBEEFCAF3** [comment]
Connections of all things covenants: https://github.com/ariard/bitcoin-contracting-primitives-wg/tree/main/primitives
Not much of a reading article but a helpful resource

**Comment by 0xBEEFCAF3** [comment]
https://bitcoinsearch.xyz/

**Comment by 0xBEEFCAF3** [comment]
https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2023-February/021444.html
[bitcoin-dev] Unenforceable fee obligations in multiparty protocols with Taproot inputs

**Comment by 0xBEEFCAF3** [comment]
[bitcoin-dev] Purely off-chain coin colouring
https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2023-February/021396.html

**Comment by 0xBEEFCAF3** [comment]
Signing support for Miniscript Descriptors #24149
https://github.com/bitcoin/bitcoin/pull/24149

**Comment by satsie** [comment]
Bitcoin Confirmation Risk Calculator & article explaining the math behind it: https://blog.lopp.net/how-many-bitcoin-confirmations-is-enough/

**Comment by 0xBEEFCAF3** [comment]
Ordinal theory handbook
https://docs.ordinals.com/overview.html

**Comment by 0xBEEFCAF3** [comment]
Codex32 new Bip32 backup mechanism 
https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2023-February/021469.html

**Comment by john-light** [comment]
Sovereign rollups on bitcoin using tapscript
https://twitter.com/lightcoin/status/1630301399358533633
