### ISSUE TITLE
Socratic Seminar 14 Reading List (March 2023)

### ISSUE THREAD

**Issue by satsie** [0xBEEFCAF3/bostonbitdevs#15]
Drop links here!

**Comment by 0xBEEFCAF3** [comment]
[bitcoin-dev] Ephemeral Anchors: Fixing V3 Package RBF againstpackage limit pinning
https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2023-January/021373.html

**Comment by 0xBEEFCAF3** [comment]
https://rollkit.dev/blog/sovereign-rollups-on-bitcoin

**Comment by btsea** [comment]
Muun submarine swaps quickly expanding UTXO set
https://twitter.com/mononautical/status/1621663167582437376

v3 Transaction Policy + Transaction Pinning
https://github.com/bitcoin/bitcoin/pull/25038
https://bitcoinops.org/en/topics/transaction-pinning/

BOLT 12
https://github.com/lightning/bolts/pull/798

**Comment by DanGould** [comment]
rust-bitcoin v0.30.0 is out https://rust-bitcoin.org/blog/release-0.30.0/

TypeScript library for miniscript descriptors released: The TypeScript-based [Bitcoin Descriptors Library](https://github.com/bitcoinerlab/descriptors) has support for [PSBTs](https://bitcoinops.org/en/topics/psbt/), [descriptors](https://bitcoinops.org/en/topics/output-script-descriptors/), and [miniscript](https://bitcoinops.org/en/topics/miniscript/). This includes support for signing directly or when using certain hardware signing devices. (discussion point: Can we do this with rust-bitcoin + wasm?)

BTCPay Server coinjoin plugin released: The Wasabi Wallet [announcement](https://blog.wasabiwallet.io/wasabiwalletxbtcpayserver/) notes that any BTCPay Server merchant can activate the optional plugin which supports the [WabiSabi](https://bitcoinops.org/en/newsletters/2020/06/17/#wabisabi-coordinated-coinjoins-with-arbitrary-output-values) protocol for [coinjoins](https://bitcoinops.org/en/topics/coinjoin/).

[BDK 1.0.0-alpha #793](https://github.com/bitcoindevkit/bdk/issues/793) is a major restructuring of the library based on the work of the [bdk_core sub-project](https://bitcoindevkit.org/blog/bdk-core-pt1/). According to the PR description, it “maintains the existing wallet API as much as possible and adds very little.” Three API endpoints with seemingly minor changes are listed in the PR description. (it has been [a long time coming](https://bitcoindevkit.org/blog/road-to-bdk-1/))

[Lightning on Blockstream Green](https://twitter.com/Blockstream/status/1638671142570594305) presumably using Greenlight, like the new [Breez SDK](https://github.com/breez/breez-sdk) announced in a recent [blog post](https://medium.com/breez-technology/lightning-for-everyone-in-any-app-lightning-as-a-service-via-the-breez-sdk-41d899057a1d), 

mempool.space explorer enhances CPFP support: The mempool.space [explorer](https://bitcoinops.org/en/topics/block-explorers/) announced [additional support](https://twitter.com/mempool/status/1630196989370712066) for [CPFP](https://bitcoinops.org/en/topics/cpfp/)-related transactions. showing the CPFP visualization could be a great way to supplement earlier discussions that garnered large interest around fee bumping (rbf). Also, mempools around the world are full!

Bank failure, reactions (https://www.federalreserve.gov/newsevents/pressreleases/monetary20230319a.htm), and FED rate hikes. Printing + rate hikes = 😵‍💫?

Balaji's PR stunt https://twitter.com/balajis/status/1636822077775941633
