### ISSUE TITLE
Socratic Seminar 15 Reading List (April 2023)

### ISSUE THREAD

**Issue by 0xBEEFCAF3** [0xBEEFCAF3/bostonbitdevs#17]
Drop Links here!

**Comment by 0xBEEFCAF3** [comment]
https://b10c.me/observations/06-linkinglion/?t

**Comment by 0xBEEFCAF3** [comment]
https://twitter.com/COLDCARDwallet/status/1644363263558430723?t=q_Mvgxk5h-0XTWIB3I665A&s=19

**Comment by 0xBEEFCAF3** [comment]
[Lightning-dev] Resizing Lightning Channels Off-Chain With Hierarchical Channels

https://lists.linuxfoundation.org/pipermail/lightning-dev/2023-March/003886.html

**Comment by DanGould** [comment]
Dhruv of BIP 324 fame gets personal https://twitter.com/dhruv/status/1648443886858309635?s=20
