### ISSUE TITLE
Socratic Seminar 16 Reading List (May 2023)

### ISSUE THREAD

**Issue by satsie** [0xBEEFCAF3/bostonbitdevs#20]
Drop links here!

**Comment by 0xBEEFCAF3** [comment]
Da fees are too damn high

https://dune.com/dgtl_assets/bitcoin-ordinals-analysis

**Comment by 0xBEEFCAF3** [comment]
https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2023-May/021620.html

**Comment by 0xBEEFCAF3** [comment]
I dont think we really talked about this enough
https://zerosync.org/zerosync.pdf

**Comment by 0xBEEFCAF3** [comment]
https://payjoin.substack.com/p/interactive-payment-batching-is-better
Interactive payment batching

**Comment by 0xBEEFCAF3** [comment]
Ledger recovery system
https://www.nobsbitcoin.com/ledger-to-launch-kyc-cloud-based-recovery-service/

**Comment by 0xBEEFCAF3** [comment]
new mempool
https://github.com/bitcoin/bitcoin/issues/27677

**Comment by 0xBEEFCAF3** [comment]
If we have time, zkcoin proposal
https://gist.github.com/RobinLinus/d036511015caea5a28514259a1bab119

**Comment by 0xBEEFCAF3** [comment]
Tx accelerator!

https://twitter.com/mempool/status/1659619347910803466

**Comment by 0xBEEFCAF3** [comment]
TBDxxx is not Ark
https://www.arkpill.me/

**Comment by satsie** [comment]
Thanks for gathering all these amazing links @0xBEEFCAF3 ! Re: TapAss (lol), it's my understanding this is just Taro, which had to be renamed. I'd put it on the reading list, but only plan to talk about it if someone from the audience brings it up and wants to lead that part of discussion.

**Comment by Chepenik** [comment]
https://twitter.com/JackTracante/status/1661114322469134362?s=20 Thread about the Justice Department bringing a case against Roman Sterlingov claiming that he was the operator of a centralized mixing service called Bitcoin Fog.
