### ISSUE TITLE
Socratic Seminar 19 Reading List (September 2023)

### ISSUE THREAD

**Issue by satsie** [0xBEEFCAF3/bostonbitdevs#24]
September BitDevs will be on Tuesday 9/12: https://www.meetup.com/boston-bitdevs/events/293840595/

Drop links here for the reading list!

**Comment by 0xBEEFCAF3** [comment]
Prime trust wallet migration mix up: https://cases.stretto.com/public/X274/12452/PLEADINGS/1245208242380000000073.pdf

Sentenial chains: https://ursus.camp/bitcoin/2023/08/10/sidechains.html

Fireblocks MPC wallet vulnerability: https://www.fireblocks.com/blog/bitforge-fireblocks-researchers-uncover-vulnerabilities-in-over-15-major-wallet-providers

**Comment by 0xBEEFCAF3** [comment]
DOS fake lightning channels: https://www.nobsbitcoin.com/dos-fake-lightning-channels/

**Comment by 0xBEEFCAF3** [comment]
Liquid opensource: https://www.nobsbitcoin.com/liquid-federation-open-sourced-its-functionary-code/

**Comment by 0xBEEFCAF3** [comment]
Not happy milk : https://www.nobsbitcoin.com/milk-sad-vulnerability-disclosure/

**Comment by 0xBEEFCAF3** [comment]
Collaborative custody with FROST
https://gist.github.com/nickfarrow/4be776782bce0c12cca523cbc203fb9d/

**Comment by sutt** [comment]
AI Lightning hackathon results: https://bolt.fun/tournaments/ai4all/overview
Winner: https://github.com/lnconsole/PhotoBolt
Also ran: https://github.com/sutt/DoorMan

**Comment by 0xBEEFCAF3** [comment]
@sutt Added

**Comment by thebrandonlucas** [comment]
[Doppler](https://github.com/tee8z/doppler): A Domain-Specific Language (DSL) for Lightning
[Satogram](https://github.com/Satograms/Satogram) - keysend every pubkey in your node's lightning graph & the pros/cons of [marketing done via lightning](https://snort.social/e/nevent1qqs228lvudned330ysd66uvgljqu4y2md0j586chgnpdex05gw0lxuqpz4mhxue69uhhyetvv9ujuerpd46hxtnfduhsyg97rkyhjjle9hja6expuc8k5trsc9q2htyexfqclm3schrr0l550ypsgqqqqqqs6jurxm)

**Comment by 0xBEEFCAF3** [comment]
@thebrandonlucas Added!
