### ISSUE TITLE
 Open Socratic Seminar 20 Reading List (Oct. 2023)

### ISSUE THREAD

**Issue by 0xBEEFCAF3** [0xBEEFCAF3/bostonbitdevs#25]

**Comment by satsie** [comment]
https://x.com/rob1ham/status/1704917235305746439?s=46&t=PtDQpC8qXN6eLrhVrXTVNA

Testnet open beta of Trident Vault, a multisig coordinator that uses miniscript

**Comment by thebrandonlucas** [comment]
https://twitter.com/BobBodily/status/1711581484254192013?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1711581484254192013%7Ctwgr%5E287ba19b65e4c1d206b32c1b2f98f0d4ea13bf8f%7Ctwcon%5Es1_&ref_url=https%3A%2F%2Fcoinpedia.org%2Fnews%2Fbitvm-a-paradigm-shift-for-bitcoin-heres-what-you-need-to-know%2F

BitVM - Turing Completeness on Bitcoin without any forks required

**Comment by 0xBEEFCAF3** [comment]
This list is now being used for our Oct. meeting on the 18th!

**Comment by thebrandonlucas** [comment]
Taproot assets on Bitcoin mainnet release:

https://lightning.engineering/posts/2023-10-18-taproot-assets-v0.3/
