### ISSUE TITLE
Socratic Seminar 24 Reading List (June 18, 2024)

### ISSUE THREAD

**Issue by satsie** [0xBEEFCAF3/bostonbitdevs#31]
https://www.meetup.com/boston-bitdevs/events/301432750

Drop links here!

**Comment by 0xBEEFCAF3** [comment]
Quantum resitance addresses 
https://github.com/cryptoquick/bips/blob/p2qrh/bip-p2qrh.mediawiki

**Comment by john-light** [comment]
Risk analysis framework for bitcoin L2s and sidechains
https://delvingbitcoin.org/t/proposed-risk-framework-for-bitcoin-l2s-and-sidechains/933

**Comment by john-light** [comment]
"ZK Rollup on Bitcoin" whitepaper, or "How to build a trustless two-way BTC peg"
https://github.com/alpenlabs/Technical-Whitepaper/blob/main/whitepaper_v085.pdf

**Comment by john-light** [comment]
CISA research https://cisaresearch.org/

**Comment by john-light** [comment]
Utreexo beta release: https://groups.google.com/g/bitcoindev/c/5GyV9af9lv4

**Comment by 0xBEEFCAF3** [comment]
https://github.com/rustyrussell/bips/blob/guilt/varops/bip-unknown-var-budget-script.mediawiki

**Comment by john-light** [comment]
SNARKnado: a practical, round-efficient SNARK verifier on bitcoin 
https://www.alpenlabs.io/blog/snarknado-practical-round-efficient-snark-verifier-on-bitcoin

**Comment by delbonis** [comment]
https://github.com/supertestnet/hedgehog

> Hedgehog - A protocol for improved layer two bitcoin payments

**Comment by delbonis** [comment]
https://delvingbitcoin.org/t/64-bit-arithmetic-soft-fork/397/49

> 64 bit arithmetic soft fork

**Comment by delbonis** [comment]
https://delvingbitcoin.org/t/mutual-exclusiveness-of-op-codes/890

> Should overlapping soft fork proposals be considered mutually exclusive?

especially post from ajtowns

**Comment by delbonis** [comment]
https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2022-September/020937.html

> [bitcoin-dev] New transaction policies (nVersion=3) for contracting protocols

More on v3 txs:

* Activation PR to Core https://github.com/bitcoin/bitcoin/pull/29496
* BIP-431 https://github.com/bitcoin/bips/blob/master/bip-0431.mediawiki
* Optech topic list https://bitcoinops.org/en/topics/version-3-transaction-relay/

**Comment by john-light** [comment]
Wasabi Wallet coinjoin coordinator shuts down...
https://x.com/wasabiwallet/status/1786083838415769673

... then 10 new coordinators appear:
https://x.com/nopara73/status/1797232582003691699

FreeSabi bot tracking wabisabi coordinator liquidity:
https://x.com/FreeSabiBot

**Comment by sutt** [comment]
**Dev Bounties with Bitcoin**
- Stacker News [policy](https://github.com/stackernews/stacker.news/?tab=readme-ov-file#we-pay-bitcoin-for-contributions) and [results](https://github.com/stackernews/stacker.news/blob/master/awards.csv)
- [Sphinx bounty platform](https://community.sphinx.chat/leaderboard)
- Also, [Zeus](https://github.com/ZeusLN/zeus/blob/master/docs/Bounties.md), [Mostro](https://github.com/orgs/MostroP2P/projects/2/views/1)

**Comment by satsie** [comment]
Thanks all for the contributions to the reading list! Closing this issue now that June's event is over. Next Boston BitDevs will be in September :)
