### ISSUE TITLE
Socratic Seminar #25 - September 24, 2024

### ISSUE THREAD

**Issue by satsie** [0xBEEFCAF3/bostonbitdevs#32]
Drop links for the reading list here!

https://www.meetup.com/boston-bitdevs/events/302918883/?slug=boston-bitdevs&eventId=302918883

**Comment by 0xBEEFCAF3** [comment]
Add a PSBT per-output field for BIP 353 DNSSEC Proofs 
https://github.com/bitcoin/bips/pull/1657

**Comment by 0xBEEFCAF3** [comment]
https://proton.me/blog/proton-wallet-launch

https://x.com/StarkWareLtd/status/1813929304209723700 STARK proofs in script

**Comment by 0xBEEFCAF3** [comment]
Frost bip https://github.com/siv2r/bip-frost-signing
Dkg bip https://github.com/BlockstreamResearch/bip-frost-dkg

**Comment by DanGould** [comment]
- [Bitcoin Core's migration to the CMake buildsystem](https://mailing-list.bitcoindevs.xyz/bitcoindev/6cfd5a56-84b4-4cbc-a211-dd34b8942f77n@googlegroups.com/](https://mailing-list.bitcoindevs.xyz/bitcoindev/6cfd5a56-84b4-4cbc-a211-dd34b8942f77n@googlegroups.com/)
  - [Optech overview](https://bitcoinops.org/en/newsletters/2024/08/16/)
  - build system and tooling has been completely overhauled
  - platform native build commands (MSVC & XCode)
  - `ninja` better than `make` (cross platform)
  - direct feedback in your editor thanks to clangd LSP
- [Silvergate Executive confirms they were pressured out of business, Nic Carter describes it as "murder, not suicide"](https://x.com/nic__carter/status/1836858969241100776)

**Comment by 0xBEEFCAF3** [comment]
CSV shield https://github.com/ShieldedCSV/ShieldedCSV/tree/main?tab=readme-ov-file

**Comment by delbonis** [comment]
https://x.com/citrea_xyz/status/1838587009478078630

> The only rollup solution to expand Bitcoin’s utility and freedom is here.
Bitcoin blockspace is now open to EVM developers for a new decentralized financial era.
> Citrea Public Testnet is LIVE on Bitcoin Testnet4

**Comment by sutt** [comment]
- [Puzzle #66](https://bitcointalk.org/index.php?topic=1306983.msg64526037#msg64526037) solved and stolen(?)
- Obligatory Trump Tx [stack](https://x.com/willcole/status/1836605366848655855)
- PlebLab [StartupDay](https://www.pleblab.dev/startup-day-cdmx) Sept 19, Mexico City

**Comment by 0xBEEFCAF3** [comment]
Added both!
Thanks @sutt & @delbonis
